---
title: "Allison Blog Post Map"
output: html_notebook
---


```{r library_load, include=FALSE}
rm(list = ls())

library(tidyverse)
library(sf)
library(viridis)
library(leaflet)
library(maps)
library(htmlwidgets)
library(tidycensus)
library(htmltools)
library(tigris)
library(reshape2)
library(ggrepel)
library(ggmap)
library(openxlsx)
library(snakecase)
library(webshot)

options(tigris_use_cache = TRUE)
```

```{r}
rm(list = ls())
countyboundaries <- get_acs(geography = "county",
                            variables = "B19013_001",
                            state = "IL",
                            geometry = T,
                            year = 2017)
```

```{r}
countyboundaries$NAME <- gsub("\\,.*","",countyboundaries$NAME)

counties <- read.xlsx("I:/BUDGET AND TAX/Graduated Rate Income Tax/2020 Report/2020 Report Data/Copy of IRS SOI 2017 IL County.xlsx", sheet = 4)

counties <- counties[-1,]
colnames(counties) <- to_snake_case(make.names(colnames(counties),unique = T))

test <- left_join(counties, countyboundaries, by = c("county" = "NAME"))
test <- st_as_sf(test)

test <- test %>% filter(region=="Downstate")
test$x_200_k_or_more_as_pct <- test$x_200_000_or_more_1*100
```

```{r}
calabels <- sprintf(
  paste0("<strong>%g%%</strong> of single filers earning over $200K in Illinois reside in <strong>%s.</strong><br/>"),
  round(test$x_200_k_or_more_as_pct,2),
  test$county) %>% 
  lapply(HTML)

callaboptions <- labelOptions(
  style = list("font-weight" = "normal", 
               padding = "3px 8px"),
  textsize = "15px",
  direction = "auto")
```

```{r}
color_200k <- colorNumeric(
  palette = c("white","blue"),
  domain = test$x_200_k_or_more_as_pct)
```


```{r}
map <- leaflet(options = leafletOptions(zoomSnap=0.1)) %>%
  addTiles() %>% 
  addPolygons(data= st_geometry(test),
              color = "black",
              fillColor = color_200k(test$x_200_k_or_more_as_pct),
              popup = calabels,
              popupOptions = callaboptions,
              weight = 2.5,
              fillOpacity = .55,
              smoothFactor = .2) %>% 
  addLegend(title = "Statewide Percentage of<br>Earners Over 200K<br>(Single Filers, By County, <br>In 2017)",
            pal = color_200k,
            values = test$x_200_k_or_more_as_pct,
            position = "topright")
saveWidget(map,"downstate_200k.html")
webshot("downstate_200k.html", file = "downstate_200k.png",
        cliprect = "viewport")
```

```{r}
rm(list = ls())
countyboundaries <- get_acs(geography = "county",
                            variables = "B19013_001",
                            state = "IL",
                            geometry = T,
                            year = 2017)
```

```{r}
countyboundaries$NAME <- gsub("\\,.*","",countyboundaries$NAME)

counties <- read.xlsx("I:/BUDGET AND TAX/Graduated Rate Income Tax/2020 Report/2020 Report Data/Copy of IRS SOI 2017 IL County.xlsx", sheet = 4)

counties <- counties[-1,]
colnames(counties) <- to_snake_case(make.names(colnames(counties),unique = T))

test <- left_join(counties, countyboundaries, by = c("county" = "NAME"))
test <- st_as_sf(test)

test <- test %>% filter(region!="Downstate")
test$x_200_k_or_more_as_pct <- test$x_200_000_or_more_1*100
```

```{r}
calabels <- sprintf(
  paste0("<strong>%g%%</strong> of single filers earning over $200K in Illinois reside in <strong>%s.</strong><br/>"),
  round(test$x_200_k_or_more_as_pct,2),
  test$county) %>% 
  lapply(HTML)

callaboptions <- labelOptions(
  style = list("font-weight" = "normal", 
               padding = "3px 8px"),
  textsize = "15px",
  direction = "auto")
```

```{r}
color_200k <- colorNumeric(
  palette = c("blue","red"),
  domain = test$x_200_k_or_more_as_pct)
```


```{r}
map <- leaflet(options = leafletOptions(zoomSnap=0.1)) %>%
  addTiles() %>% 
  addPolygons(data= st_geometry(test),
              color = "black",
              fillColor = color_200k(test$x_200_k_or_more_as_pct),
              popup = calabels,
              popupOptions = callaboptions,
              weight = 2.5,
              fillOpacity = .55,
              smoothFactor = .2) %>% 
  addLegend(title = "Statewide Percentage of<br>Earners Over 200K<br>(Single Filers, By County, <br>In 2017)",
            pal = color_200k,
            values = test$x_200_k_or_more_as_pct,
            position = "topright")
saveWidget(map,"collar_200k.html")
webshot("collar_200k.html", file = "collar_200k.png",
        cliprect = "viewport")
```