---
title: "Chicago Maps"
author: "Drazzel Feliu"
date: "6/18/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r library_load, include=FALSE}
rm(list = ls())

library(tidyverse)
library(sf)
library(viridis)
library(leaflet)
library(maps)
library(htmlwidgets)
library(tidycensus)
library(htmltools)
library(tigris)
library(reshape2)
library(ggrepel)
library(ggmap)

options(tigris_use_cache = TRUE)
```

```{r shapefiles, include=FALSE}
# Larger Boundaries - County and City
countyboundaries <- get_acs(geography = "county",
                            variables = "B19013_001",
                            state = "IL",
                            county = "Cook",
                            geometry = T,
                            year = 2017)

cityboundary <- read_sf("geo_export_72cf3d72-fa82-4448-a382-c9dd6dcb4fd2.shp")
cityboundary <- st_union(cityboundary)
cityboundary <- st_transform(cityboundary,
                             4326)

# Neighborhood and CA boundaries
communityareas <- read_sf("geo_export_72cf3d72-fa82-4448-a382-c9dd6dcb4fd2.shp")

neighborhoods <- read_sf("Neighborhoods_2012b.shp")
neighborhoods <- st_transform(neighborhoods, 
                              4326)

# Tract Level boundaries - City Only
tractlevel <- get_acs(geography = "tract",
                      variables = "B19013_001",
                      state = "IL",
                      county = "Cook",
                      geometry = T,
                      year = 2017,
                      cb = FALSE)

# Usable Data
data <- read_csv("Per_Capita_Income.csv")

communityareas$community <- str_to_title(communityareas$community)

full_data <- merge(communityareas,
                   data, 
                   by.x="community", 
                   by.y="COMMUNITY AREA NAME")

colnames(full_data) <- str_to_lower(colnames(full_data)) %>% str_replace_all(.," ","_")
```

------------------------------------------------------------------------------------------------------
EXPERIMENTAL

```{r}
# Filter tracts by whether they reside within the city boundaries
class(tractlevel)
class(cityboundary)

test1 <- cityboundary
test2 <- tractlevel

newthing <- st_join()

```

------------------------------------------------------------------------------------------------------

```{r labels}
calabels <- sprintf(
  paste0("<strong>Name: </strong>%s<br/>"),
  communityareas$community) %>% 
  lapply(HTML)

callaboptions <- labelOptions(
  style = list("font-weight" = "normal", 
               padding = "3px 8px"),
  textsize = "15px",
  direction = "auto")

neighlabels <- sprintf(
  paste0("<strong>Name: </strong>%s<br/>"),
  neighborhoods$PRI_NEIGH) %>% 
  lapply(HTML)

neighlaboptions <- labelOptions(
  style = list("font-weight" = "normal", 
               padding = "3px 8px"),
  textsize = "15px",
  direction = "auto")
```

```{r community_areas}
leaflet() %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(data= st_geometry(communityareas),
              color = "black",
              fillColor = NULL,
              popup = calabels,
              popupOptions = callaboptions,
              weight = 2.5,
              fillOpacity = .001,
              smoothFactor = .2)
```


```{r neighborhoods}
leaflet() %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(data= st_geometry(neighborhoods),
              color = "black",
              fillColor = NULL,
              popup = neighlabels,
              popupOptions = neighlaboptions,
              weight = 2.5,
              fillOpacity = .001,
              smoothFactor = .2)

```

```{r}
ggplot() + 
  geom_sf(full_data,
          mapping = aes(fill=per_capita_income, 
                        color=per_capita_income),
          inherit.aes = F,
          alpha=.99) + 
  scale_fill_viridis() + 
  scale_color_viridis() +
  theme_minimal() + 
  ggtitle("Per Capita Income By Community Areas in Chicago",
          subtitle = "(A chance to look at some numbers)")
```


